create database QUANLYBANHANG_LTTQ

use QUANLYBANHANG_LTTQ

create table NHANVIEN
(
	NVID varchar(4),
	HOTEN VARCHAR(40),
	NGLV SMALLDATETIME,
	NGSINH SMALLDATETIME,
	THUONG TINYINT,
	CV_ID VARCHAR(4)
	CONSTRAINT PK_NV PRIMARY KEY (NVID)

)

CREATE TABLE CHUCVU
(
	CVID VARCHAR(4),
	TENCV VARCHAR (40),
	LUONG INT,
	CONSTRAINT PK_CV PRIMARY KEY (CVID)
)



CREATE TABLE KHACHHANG
(
	KHID VARCHAR(4),
	HOTEN VARCHAR(40),
	DIACHI VARCHAR(50),
	SDT VARCHAR (10), 
	NGDK SMALLDATETIME,
	DOANHSO TINYINT,
	LOAIID VARCHAR(4)
	CONSTRAINT PK_KH PRIMARY KEY (KHID)
)

CREATE TABLE LOAIKH
(
	LOAIID VARCHAR(4),
	TENLOAI VARCHAR (40),
	UUDAI INT,
	CONSTRAINT PK_LKH PRIMARY KEY (LOAIID)
)



CREATE TABLE SANPHAM
(
	SPID VARCHAR(4),
	TENSP VARCHAR(40),
	LOAIID VARCHAR(4),
	NUOCSX VARCHAR (10), 
	GIABAN MONEY,
	GIANHAP MONEY,
	DVT TINYINT,
	SOLUONG INT,
	SLTT INT,
	MOTA VARCHAR(500),
	CONSTRAINT PK_SP PRIMARY KEY (SPID)
)

CREATE TABLE LOAISP
(
	LOAIID VARCHAR(4),
	TENLOAI VARCHAR (40),
	MOTA VARCHAR(100),
	CONSTRAINT PK_LSP PRIMARY KEY (LOAIID)
)




CREATE TABLE DTCC
(
	DTID VARCHAR(4),
	TENDT VARCHAR (40),
	SDT VARCHAR(10),
	NGDT SMALLDATETIME,
	CONSTRAINT PK_DT PRIMARY KEY (DTID)
)

CREATE TABLE HDBH
(
	SOHD_BH VARCHAR(4),
	NGHD SMALLDATETIME,
	KHID VARCHAR(4),
	NVID VARCHAR(4),
	TRIGIA MONEY,
	CONSTRAINT PK_HDBH PRIMARY KEY (SOHD_BH)
)


CREATE TABLE HDNH
(
	SOHD_NH VARCHAR(4),
	NGNHAP  SMALLDATETIME,
	DTID VARCHAR(4),
	NVID VARCHAR(4),
	TRIGIA MONEY,
	CONSTRAINT PK_HDNH PRIMARY KEY (SOHD_NH)
)

CREATE TABLE CTHDNH
(
	SOHD_NH VARCHAR(4),
	SPID VARCHAR(4),
	SL TINYINT,
	CONSTRAINT PK_CTHDNH PRIMARY KEY (SOHD_NH, SPID)
)

CREATE TABLE CALAMVIEC
(
	CAID VARCHAR(4),
	THU VARCHAR(15),
	GIO_BD DATETIME,
	GIO_NGHI DATETIME,
	CONSTRAINT PK_CLV PRIMARY KEY (CAID)
)

CREATE TABLE CT_LAMVIEC
(
	NVID VARCHAR(4), 
	CAID VARCHAR(4),
	NGAYLAM SMALLDATETIME,
	TRANGTHAI VARCHAR(20),
	CONSTRAINT PK_CTLV PRIMARY KEY (CAID, NVID)
)

CREATE TABLE HANHDONG
(
	TIME_HD DATETIME,
	NVID VARCHAR(4),
	SOHD VARCHAR(4),
	LOAIHD VARCHAR(4)
	CONSTRAINT PK_HD PRIMARY KEY (NVID, SOHD, LOAIHD)
)

CREATE TABLE DOANHTHUNGAY
(
	TODAY DATETIME,
	SLHOADON INT,
	SLDONNHAP INT,
	DOANHTHU MONEY,
	TONGCHI MONEY
	CONSTRAINT PK_DTN PRIMARY KEY (TODAY)
)
CREATE TABLE DOANHTHUTHANG
(
	THISMONTH DATETIME,
	DOANHTHU MONEY,
	TONGCHI MONEY
	CONSTRAINT PK_DTT PRIMARY KEY (THISMONTH)
)

CREATE TABLE DOANHTHUNAM
(
	THISYEAR DATETIME,
	DOANHTHU MONEY,
	TONGCHI MONEY
	CONSTRAINT PK_DTNAM PRIMARY KEY (THISYEAR)
)

 -- CAC KHOA NGOAI --

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV FOREIGN KEY (CV_ID) REFERENCES CHUCVU(CVID)
ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KH FOREIGN KEY (LOAIID) REFERENCES LOAIKH(LOAIID)
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP FOREIGN KEY (LOAIID) REFERENCES LOAISP(LOAIID)

ALTER TABLE HDBH ADD CONSTRAINT FK_HDBH FOREIGN KEY (NVID) REFERENCES NHANVIEN(NVID)
ALTER TABLE HDNH ADD CONSTRAINT FK_HDNH FOREIGN KEY (NVID) REFERENCES NHANVIEN(NVID)
ALTER TABLE CTHDNH ADD CONSTRAINT FK_CTHDNH FOREIGN KEY (SPID) REFERENCES SANPHAM(SPID)
ALTER TABLE CTHDNH ADD CONSTRAINT FK_CTHDNH2 FOREIGN KEY (SOHD_NH) REFERENCES HDNH(SOHD_NH)

ALTER TABLE CT_LAMVIEC ADD CONSTRAINT FK_CT_LV FOREIGN KEY (NVID) REFERENCES NHANVIEN(NVID)
ALTER TABLE CT_LAMVIEC ADD CONSTRAINT FK_CT_LV2 FOREIGN KEY (CAID) REFERENCES CALAMVIEC(CAID)


--CAC DIEU KIEN --